### ISSUE TITLE
replace bgl with gpu module

### ISSUE THREAD

**Issue by atticus-lv** [mmmrqs/bl_ui_widgets#10]
Notice that the blender will remove bgl in 4.0(or 3.6 maybe), we should change it earlier

**Comment by mmmrqs** [comment]
> Notice that the blender will remove bgl in 4.0(or 3.6 maybe), we should change it earlier

Hi @atticus-lv - thanks for the heads up.  That upgrade is in my to-do list, but I do not have any estimate re when I am going to have time for doing that.  Blender is really a moving target.

**Comment by atticus-lv** [comment]
Hi @mmmrqs, just open a pr #11 to fix this, I am sure that it can work well on the example, may you take a little while to check it? 
![image](https://user-images.githubusercontent.com/64118610/236900272-13aa6e37-7eb4-480b-ba93-213bec8892c1.png)

**Comment by mmmrqs** [comment]
@atticus-lv, **thank you so much for providing the changes**, that is much helpful and appreciated.  I accepted the pull request and have the code merged.  There was a little thing of my own that went together with this release, just a new 'time_step' class level property that I've added so that the developer can customize the interval in seconds between timer events. On the bl_ui_widget.py I noticed that there were many changes in your version regarding pep-8 standards which I haven't accepted them all because sometimes I prefer to compromise the standards in order to have better reading of similar clustered data (using extra spaces for alignment, for example). I can change my mind in the future though.
